;; testcase for max deep nested blocks(nested block 1024)

(module
  (func (export "test") (result i32)
        (local i32)
        (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block
            (block (drop (i32.add (local.get 0) (i32.const 1)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

        (i32.const 1))
)

(assert_return (invoke "test") (i32.const 1))
